import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import utilStyles from '../styles/utils.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Serhii's CV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image 
          priority
          src="/images/profile.jpg"
          className={utilStyles.borderCircle}
          height={144}
          width={144}
          alt={'Serhii Kryvenko'} />
        <h1 className={styles.title}>
          <a href="https://docs.google.com/document/d/17K-lX9M1hY1Wzbnh32mCWglPe17Ginx_/edit?usp=sharing&ouid=114415959102331654958&rtpof=true&sd=true">Serhii Kryvenko's CV</a>
        </h1>

        <p className={styles.description}>
          My objective is to obtain a Software Engineer position.
          <br/> Where my technical and communication skills will contribute to the success of your department and my personal growth.
          <br/>Interested in becoming a professional in IT-world.
        </p>

        <div className={styles.grid}>
          <a href="https://github.com/MadWolfInTheHub/Airport_board" className={styles.card}>
            <h2>Airport on React-Redux Source Code &rarr;</h2>
            <h3>Description: </h3>
            <p>
              flights search clone of <code>https://iev.aero/ </code>with real list of flights received from this server.
            </p>
          </a>

          <a href="https://glowing-naiad-e7dc88.netlify.app/" className={styles.card}>
          <h2>Airport on React-Redux App &rarr;</h2>
            <Image 
              priority
              src="/images/airport_app.png"
              height={167}
              width={260}
              alt='airport app'/>
          </a>

          <a href="https://github.com/MadWolfInTheHub/Calendar-react" className={styles.card}>
            <h2>Calendar on React Source Code &rarr;</h2>
            <h3>Description: </h3>
            <p>
              clone of google-calendar. You can create/edit/delete events and this information will be saved on server
            </p>
          </a>

          <a href="https://mellow-hummingbird-13d60b.netlify.app/" className={styles.card}>
          <h2>Calendar on React App &rarr;</h2>
            <Image 
              priority
              src="/images/calandar_on_react.png"
              height={167}
              width={260}
              alt='Serhii Kryvenko'/>
          </a>

          <a
            href="https://github.com/MadWolfInTheHub/Website-layout"
            className={styles.card}
          >
            <h2>Website layout Source Code &rarr;</h2>
            <h3>Description: </h3>
            <p>
              layout by Figma template. Responsive and multi-device
            </p>
          </a>

          <a href="https://madwolfinthehub.github.io/Website-layout/" className={styles.card}>
          <h2>Website layout &rarr;</h2>
            <Image 
              priority
              src="/images/website_layout.png"
              height={167}
              width={260}
              alt='website_layout'/>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.facebook.com/sergey.krivenko.56"
        >
          <span className={styles.logo}>
            <Image src="/images/facebook_logo.png" alt="Vercel Logo" width={48} height={48} />
          </span>
          My Facebook
        </a>

        <a
          href="https://www.linkedin.com/in/serhii-kryvenko-b6099a74/"
        >
          <span className={styles.logo}>
            <Image src="/images/linkedIn_logo.png" alt="Vercel Logo" width={56} height={56} />
          </span>
          My LinkedIn
        </a>

        <a
          href="mailto:krivenko.serhii@icloud.com"
        >
          <span className={styles.logo}>
            <Image src="/images/mail_logo.png" alt="Vercel Logo" width={68} height={48} />
          </span>
          Send me an email
        </a>

        <a
          href="tel:+8615698325581"
        >
          <span className={styles.logo}>
            <Image src="/images/phone_logo.png" alt="Vercel Logo" width={40} height={48} />
          </span>
          Call me
        </a>
      </footer>
    </div>
  )
}
